import fs from 'node:fs';
import path from 'node:path';

/**
 * Build an override compose file that:
 *   1. Neutralizes hard-coded container_name entries (preserving them as
 *      network aliases), AND
 *   2. Injects runtime env vars into every service via `environment:`.
 *
 * Build-time Vite vars are NOT passed as build args here. Instead,
 * stages.js writes a `.env.production` file into each frontend's build
 * context. This works without requiring ARG declarations in the repo's
 * own Dockerfile.
 *
 * Returns { overridePath, args } where `args` is the `-f ...` sequence.
 */
export function writeComposeOverride(repoRoot, baseFileName, inspected, envVars = []) {
  const { containerNames, serviceNames } = inspected;
  const hasNames = containerNames && Object.keys(containerNames).length > 0;
  const hasEnv = Array.isArray(envVars) && envVars.length > 0;

  if (!hasNames && !hasEnv) {
    return { overridePath: null, args: ['-f', baseFileName] };
  }

  const targetServices = hasNames
    ? Object.keys(containerNames)
    : (serviceNames || []);

  if (targetServices.length === 0) {
    return { overridePath: null, args: ['-f', baseFileName] };
  }

  const lines = ['# Generated by CloudShip — do not edit', 'services:'];

  for (const service of targetServices) {
    lines.push(`  ${service}:`);

    if (hasNames && containerNames[service]) {
      lines.push(`    container_name: null`);
      lines.push(`    networks:`);
      lines.push(`      default:`);
      lines.push(`        aliases:`);
      lines.push(`          - ${containerNames[service]}`);
    }

    if (hasEnv) {
      const applicable = envVars.filter(
        (r) => !r.serviceName || r.serviceName === service,
      );

      if (applicable.length > 0) {
        lines.push(`    environment:`);
        for (const row of applicable) {
          if (!row.key) continue;
          const val = String(row.value ?? '')
            .replace(/\\/g, '\\\\')
            .replace(/"/g, '\\"');
          lines.push(`      ${row.key}: "${val}"`);
        }
      }
    }
  }

  lines.push('');

  const overridePath = path.join(repoRoot, 'docker-compose.cloudship.yml');
  fs.writeFileSync(overridePath, lines.join('\n'));
  return {
    overridePath,
    args: ['-f', baseFileName, '-f', 'docker-compose.cloudship.yml'],
  };
}